### ISSUE TITLE
error in fwhr calculator

### ISSUE THREAD

**Issue by SergiofBeltran** [TiesdeKok/fWHR_calculator#1]
_No face found or face orientation not suitable for calculating FWHR.

If this error pops up for all pictures, feel free to open an issue on the GitHub page so that I can look into it._

in every photo that i insert in.

**Comment by TiesdeKok** [comment]
I have rebooted the server. I will look a.s.a.p into fixing what is crashing it. 

Thanks for the heads-up!

**Comment by SergiofBeltran** [comment]
thanks!!!

**Comment by SergiofBeltran** [comment]
i think it`s happened again

**Comment by TiesdeKok** [comment]
I believe the crashes are happening due to memory spikes caused by very big images. To combat this I have added functionality to automatically resize over-sized images. This should solve the problem. :smile:
