### ISSUE TITLE
Need help with fWHR calculator 

### ISSUE THREAD

**Issue by evanmostafa1** [TiesdeKok/fWHR_calculator#4]
Hi,
I am a medical student and wish to use your calculator for a facial analysis study. I am new to the world of computer programs and need a little help. I've installed XCode, CMake, Homebrew, Pytho, built dlib and installed the face_recognition package within terminal. What are my next steps? I went to your Jupyter Notebook that has the calculator source code but am not sure what to do with it.

**Comment by TiesdeKok** [comment]
Running the code is simple:    

All the code up to the `example` header defines the functions, once you ran that you can use the `get_fwhr()` function to calculate it.
